### ISSUE TITLE
勇哥是否可以在增加一个功能

### ISSUE THREAD

**Issue by huang770101** [yonggekkk/openwrt_win64-ddns-cdnip#1]
勇哥，是否可以增加一个判断条件：
目前这个脚本中每次执行都是删除上一版的IP地址包，然后重新下载新的IP地址并解压生产新的IP地址文件。是否可以增加一个判断条件，在配置文件中增加使用原来下载的IP地址包，或重新下载IP地址包，使用户可以自行选择是否需要现在最新IP地址包。

**Comment by yonggekkk** [comment]
反代IP更新与不更新选择？？

**Comment by huang770101** [comment]
勇哥就是，每天执行任务时，软件都会自动下载最新的IP地址文件，是否可以设置成用户自己选择是否需要下载，如果不需要下载则使用上次下载的，如果需要下载再重新下载最新的IP地址文件。

**Comment by yonggekkk** [comment]
> 勇哥就是，每天执行任务时，软件都会自动下载最新的IP地址文件，是否可以设置成用户自己选择是否需要下载，如果不需要下载则使用上次下载的，如果需要下载再重新下载最新的IP地址文件。

官方ip是不会下载的，因为就那些ip！反代会自动下

**Comment by huang770101** [comment]
勇哥好！那是否可以设置一下，由用户决定是否下载最新的反代IP，如果比较麻烦就算了，谢谢勇哥的耐心解答。万分感谢！！

**Comment by yonggekkk** [comment]
> 勇哥好！那是否可以设置一下，由用户决定是否下载最新的反代IP，如果比较麻烦就算了，谢谢勇哥的耐心解答。万分感谢！！

反代IP容易失效，所以才每次都下载更新的
