### ISSUE TITLE
下载测速为0且获取DNS失败导致DNS解析只增不减

### ISSUE THREAD

**Issue by hb-0** [yonggekkk/openwrt_win64-ddns-cdnip#11]
不知道是不是网络原因，前一天用得还好好的脚本。再次运行就如标题所示了。

**Comment by yonggekkk** [comment]
八成网络原因！重装下看

**Comment by hb-0** [comment]
选1重置后，重新填一遍配置后，确实好了……
之前好像是修改了下配置，再改回原来的配置，但是始终如标题那样。
