### ISSUE TITLE
cdnopw.sh: line 1: syntax error near unexpected token `<'

### ISSUE THREAD

**Issue by chardsonRi** [yonggekkk/openwrt_win64-ddns-cdnip#12]
脚本安装出现错误 **cdnopw.sh: line 1: syntax error near unexpected token `<'**

cdnopw.sh: line 1: `<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: "gitlab.com",cType: 'managed',cNounce: '82005',cRay: '81ddc342bf610a86',cHash: 'ae2f08287155ec3',cUPMDTk: "\/rwkgyg\/cdnopw\/raw\/main\/cdnopw.sh?__cf_chl_tk=5YysLcuv4a8P6pH2VsrB4JoeyD_n3U3r.p4VNFtzbqA-1698607089-0-gaNycGzNCqU",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/rwkgyg\/cdnopw\/raw\/main\/cdnopw.sh?__cf_chl_f_tk=5YysLcuv4a8P6pH2VsrB4JoeyD_n3U3r.p4VNFtzbqA-1698607089-0-gaNycGzNCqU",md: "7BXMf_aG4MHgh.Nw4.wTrNYc0q4LRt6jFToZ6pra2K4-1698607089-0-AdfzryD1KtUqERVQ63P-7HzhpxSPNBChOvZl5f_s00ldoYQx-Pi3q5rfFDr5bM3KOguSuhDZ9EUH8Y9f63Af6LCd114qXzzUGLsXEE4MXevO8AnFCHRvYdHJJy8wbPRlIwZDnh4pQeMjB0eQupqS56L_m6wCvO9XBgkQJl9M11evsEkFyqMei4TOLOgH0ZVgfYC7wLeCFwyzCjiRzHEDOLBeo5GH3NdHhZ5EfeiZnAixFSHgjodyOcGoix4COr-jYsGRbVdqNJtYn_JVKmkmQhy9PF0oZwxMJUuHNFxr6MGAKXOBoGpQSNEOFnB_ttBdatCEzO3NfQlc4uVbCYXt7JQ-F_N1vZuson5V7UR1jjv62vONlIlvSLrfF1whyNjfD7JTNYmQdBYYKy0x2dv4aQBODJxmDFJXcctE0U2FNRx4ux32OPfax96kJ1EPYFAoy_3-GWJpsHGLU_CQoHPUA1smPQCLybXwG6Q8rY58eFPMpLDe8IFLwrqh-hC5mqNMqxzDCvUhQzNkiPV4d3McSgJhGLd22Ec9-8rcuHjsyLwpwacGDQG2ExQfC7L9nhrrUS0QAyrnlI6MAuSwCVBQeV7dUrcRtSriJDwPqUTDKb0lL-fqtaOD74f-5BPhqo8I8Z5X3RNwLp8MMt_M2UfAFjQT4-ZAyR2uetPzOZc8jJwRqZj99dfay75P_l_K2a2n2VddA_RffKM-nwhRexHTn3UR3qUvqtYpitQVcyPkccipa5llL8wTcOrsByjsriNR9uGeJOmum2t0k051hCBT48utdZqQ3-W71elRjUqgmjNX2rW_TnpDDGjPFEy-AWfv6SBDQfLnsN3zCzDFel9atmVJTPfA9aHiMO08JQK4jyPFs3ZBudSXLevtDg1sDVWthcdoT8VT4GF5gvda2MDccFYv_MVr0vMc-bAvfndKix_vZtKiqeSoQeDYRTdGAiVdVD916ceRBnqSxPEyQN9XDhPVF_2MPpZ5k0QUjvI7MnWVRmyKReU7FzFmmT_3FOnIbkuCSP21vpVVQu0I39Ix_AiD4P3ZjTAM8PfZeIG-Hm9XDeKpl6PkcG2vWbr6PZQ0DQf4KmCLoyvq-nAQCBCthhKmoAJpPBcMrF1uGhBvyDk75DYvid2Wm5cemvPKEe3QIFsIPgRvyT2Js8M6ReXErHkCJiE_cXopMkVQAYH3bwVu-CoLBXT36GgcBwky3a9EQow9UEFc_ADnCzU8zVNZW7TZIVJCnE7aeCdZQOheYAbcowAZ7an7YWsc1PXSY8GGvK61aJrTDKAJUrUnSkw8vmVp4_0-cR1OYIFwzshy9DHVJO7M18GbnqXo5TxcAKhqA4ZWve6oj4ckP_J4EEIB9zfzs1_72Cd8NCJ2FxG_c8753WxIXp6Caq1VIvFXlIfBFjtREf4iq_-4Wmio9r7dJ5rlUHm-ogRsNRde7ASSkzWlzPyDs0L9elZdYGDRN-Q5_43Pkl4pwE9O2VFvKiVNKBo9RYecuQSA8jE-tqMlA4cP4KEKtP0HTdHqLViHqlnz0YUiTyXt8sBftrelG1TULdWVRb-vxQVhnr7N4VGSKayHe3wji127cUbiFhIpIEqlXO5M0-T-dXlsOnPeeI8CVuFN4T3SxzKtXflz_W4tUwkAW-lAMBB-VwXR-IBcdivGbn8UQU45dvjzWWWIDuT21iQQyJiAGJhYznbQ2fpOmNNBjTJfbLmkYOWKmFOSMTAGiippkVjCS0d62ePRGYVF3Lyoq65YIxxa97hegtjoTKhegt5TOYNOuh5xhaRs7cW_7tsbsj4dWlchVEBp6NZ2JdTWRTcs33vXLGG4ECy3oWCDR8sJF4F32WSe_oKMK3C7M3tKdOWLiZw5e6XtGdYU1LATqJGotcQJ9PWdXUOauZ-iEYkZxvRBs1AkDWDw2f4uiqTbhKlawm2GNf5ZHJsbPPVmJMUL1Z9CuBKzdS27QWDgdTGStdFNcySE6jxSkOBc0K34vO51Ybm73iYddcQWN6HtIwj_HTYvZSZslwBxxzl_8V2nUHFNBgmX0paGJelIqZ_xMs09QosIbrGpD7NBD0Eh-IgyJrbxnokH5HPSOpk22NP30mJkYHNDORg7ziPN5GNOzqQLjjvLnbmRoWnF7tzGzHadFtSAOh7aG_dmsrZNfz82VW_fW_7nu3ZnOSA4T00i-uo5XYx5d4YNlkb2dcyAczwVqujEXnDM_crTKSZ0n-cuDJve4Coh2OHt9poFX8euPBSO9cnaAeOgRjPZrVqX9oSAeqKCY8zpX5U-WPxboWFfkxVvIWF6OZCrsbVhyDnM9iFBY8orycOwXi_HDva-09S8bCfv0FbI9CyVYLTBTTWUM26bNAz_Y1HRSlTBZKIzJeDWbi03tna5DZus-MYiKY3cswE5R5iG__4HSNtx3QNLqa2ON-E477zLagRZO3JoJquZxtUkxDTFO02SD0QZQh_7YNt4aI9ExXu_QVSD6gMbk4OQCs91p51ILDb3MogHmWhcGwUt0naqdGMz4Ccmp7Xhd3rJC1VBt4KPOPLbgu3Gi0ILRYbDjwOycvByX3c6NeOUn-4ZWkb-W7gCseGiW5oFdiH_JNDxOCUf4IIgzO9MN3_bMuSSV2E0r0T3pvM-2AMjwLS9vswvhyZxfZp0f3i4gygvENGpf421sqMJ",cRq: {ru: 'aHR0cHM6Ly9naXRsYWIuY29tL3J3a2d5Zy9jZG5vcHcvcmF3L21haW4vY2Rub3B3LnNo',ra: 'Y3VybC84LjQuMA==',rm: 'R0VU',d: 'FIpAFiziLILrHKAamkE5aBp3yq2E2GY6ykXvTB++U3QmBm4OBn+nstfkr9kzpPKWYkYhn9ziSYrBjIJYNtBqpA0x4/D/WWHSmGKQkgr1y9M5fQjcn6oKM/pyvj3VVE4/XchB4S+CEnpxsO6veyAD7gDkNnI0FvaFTPfXN4lwfqDqxcgArzHeOJ7yWti6IysR9cdJK13W12qZzk7Ucmnl+TQVsJMb4nFVcg2RjOVIwcgIiWXH9UXmg+Se8VraovPO4ARlDRwbaxhN14w0nezFOYb/lvNDGbhAmNc//PCrKxqRKq9l7Qvsrw2IJ24BYADQJynGyOI6u6cXClaJHe1q00KkRIjaKVDnhs7ulg02Dh+lU7wIVVmlFZ6tCvd3l2WG46jj4/a4ME0BwbaSe6ae07oKgMPw8G9GwbbOaXXkxrC0HLT9920HokQJx9qrMGZek84s1/K6gjHSOzTqNiRQDJuwXzaiW6pIIxmXrV7L/wI=',t: 'MTY5ODYwNzA4OS4wODUwMDA=',cT: Math.floor(Date.now() / 1000),m: '7b+lU/GafNuvY0ciQqEo16xs1et42PZNMXBBCWDLgsQ=',i1: 'mpYRxBHeZcXgk2s1UsskaA==',i2: 'xkPIjYPngpPP4uoMjDAbWw==',zh: 'UnJDyo9FrWqFHAM0dnr3Qrw4Ll86sU7CDCiveOM3u04=',uh: 'F20Tx4X4PHV+2Q7oGaTcNODjxGvofpZg/mO+RSS8M+E=',hh: 'lGQbzypQ55vDVgAzrKu7GNtEf1PrcZK3oqezycJ79vw=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=81ddc342bf610a86';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/rwkgyg\/cdnopw\/raw\/main\/cdnopw.sh?__cf_chl_rt_tk=5YysLcuv4a8P6pH2VsrB4JoeyD_n3U3r.p4VNFtzbqA-1698607089-0-gaNycGzNCqU" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>'

**Comment by ymyuuu** [comment]
建议开科学试试

**Comment by yonggekkk** [comment]
卸载重装看
