### ISSUE TITLE
最近几天优选IP总是无法解析到域名

### ISSUE THREAD

**Issue by ntbowen** [yonggekkk/openwrt_win64-ddns-cdnip#14]
我是通过软路由跑脚本每天优选域名解析到域名，最近连续几天发现更新域名失败，新的优选IP无法解析到域名，我试着通过脚本删除CF域名指定名称解析记录也失败，返回信息“获取 DNS 记录失败”。我在CF手动删除DNS记录，然后重新安装脚本，运行后依然无法将IP解析到域名，CF邮箱、区域 ID、Global API Key都正确，脚本能够正常登录CF，同时域名也是有效的，我手动在CF添加DNS记录也是可用的。

**Comment by yonggekkk** [comment]
把节点换成非CDN节点试试

**Comment by ntbowen** [comment]
> 把节点换成非CDN节点试试

应该不存在CDN节点的情况，机场专线，刚开始用的时候域名解析都是正常的

**Comment by Jerry199022** [comment]
昨天还可以 今天就不行了 试了几次都不能导入到cf

正在更新解析：多个优选IP解析到一个域名。请稍后...
获取 DNS 记录失败
导入IP地址 193.122.110.51 失败
导入IP地址 132.226.229.65 失败
导入IP地址 132.145.94.128 失败
导入IP地址 152.70.92.10 失败
导入IP地址 193.123.245.132 失败

请稍等，对优选反代IP进行地区识别，最多显示前10个IP
IP地址 193.122.110.51 的地区是: KR
IP地址 132.226.229.65 的地区是: KR
IP地址 132.145.94.128 的地区是: KR
IP地址 152.70.92.10 的地区是: KR
IP地址 193.123.245.132 的地区是: KR

**Comment by Jerry199022** [comment]
补充一下用"4.删除CF域名指定名称解析记录"会显示"获取 DNS 记录失败"

**Comment by yonggekkk** [comment]
> 补充一下用"4.删除CF域名指定名称解析记录"会显示"获取 DNS 记录失败"

是的，这个也是基于本地环境的，试试一个IP对一个域名

**Comment by ntbowen** [comment]
> > 补充一下用"4.删除CF域名指定名称解析记录"会显示"获取 DNS 记录失败"
> 
> 是的，这个也是基于本地环境的，试试一个IP对一个域名

我就是设置一个IP对一个域名，结果也是失败

**Comment by Jerry199022** [comment]
> > 补充一下用"4.删除CF域名指定名称解析记录"会显示"获取 DNS 记录失败"
> 
> 是的，这个也是基于本地环境的，试试一个IP对一个域名

奇怪是所有设置没变 昨天之前还可以 今天开始出问题.

**Comment by yonggekkk** [comment]
换VPS上跑跑看

**Comment by ntbowen** [comment]
> 换VPS上跑跑看，这几天很多人都在反馈这问题，应该网络问题

VPS上跑正常

**Comment by yonggekkk** [comment]
这几天敏感。。过几天再说吧
