### ISSUE TITLE
优选官方不成功，反代可以成功，但是不通

### ISSUE THREAD

**Issue by hbzmt** [yonggekkk/openwrt_win64-ddns-cdnip#17]
我的环境是电信，软路由下优选官方IP不成功，反代IP可以优选成功，也能推送到域名解析，就是节点不通，无论是cloudflare下的workers或者vps用你的[Sing-box精装桶一键四协议共存脚本]搭建的节点都不通，试着windows下直连ping推送后的域名，也不通。
我用的是smartdns+passwall，试着把smartdns关了也不行。
反而是使用你之前的教程[CDN优选域名V23.8.18(电脑win64).exe]选出来的域名都没有问题，麻烦帮忙看下大概出什么问题了，谢谢！

**Comment by yonggekkk** [comment]
手机上测试下，直接单个IP测试

**Comment by hbzmt** [comment]
昨晚试过了，手机开热点，笔记本连热点，节点是可以的。电报方便沟通下吗，刚在你TG群组里找了半天

**Comment by hbzmt** [comment]
现在在办公室，节点也是不通的

**Comment by hbzmt** [comment]
> > 昨晚试过了，手机开热点，笔记本连热点，节点是可以的。电报方便沟通下吗，刚在你TG群组里找了半天
> 
> 直接在群里发消息即可

好的

**Comment by hbzmt** [comment]
> > > 昨晚试过了，手机开热点，笔记本连热点，节点是可以的。电报方便沟通下吗，刚在你TG群组里找了半天
> > 
> > 
> > 直接在群里发消息即可
> 
> 好的

我在侃侃侃群组讨论的群里提问了，麻烦看下，谢谢
