### ISSUE TITLE
反代ip的时候选择80端口到ip.txt会把8080和8880端口一起加进去

### ISSUE THREAD

**Issue by q916442926** [yonggekkk/openwrt_win64-ddns-cdnip#18]
反代ip的时候选择80端口到ip.txt会把8080和8880端口一起加进去,造成这边测速和优选出来后有重复

**Comment by q916442926** [comment]
![image](https://github.com/yonggekkk/openwrt_win64-ddns-cdnip/assets/127854704/9a91e77d-7cca-4af1-87a3-edd6aec126ba)
然后8080然后最终合成的ip好像也少了

**Comment by yonggekkk** [comment]
已装下，已修复
