### ISSUE TITLE
大佬，关于优选IP后的一个问题

### ISSUE THREAD

**Issue by lslove10010** [yonggekkk/openwrt_win64-ddns-cdnip#19]
大佬，就是优选IP后不论我是用IP还是解析的域名，油管，谷歌都正常，但是只要是挂载在cf上的网站就是无法访问，包括cf官网，查看了一下网站的证书，提示如下

“与此站点的连接不安全

此网站没有证书。

由于此连接不安全，因此信息(如密码或信用卡)不会安全地发送到此网站，并且可能被其他人截获或看到。

[​​了解详细信息](https://go.microsoft.com/fwlink/?linkid=2151738)”，

**Comment by yonggekkk** [comment]
脚本是用刚更新的吗？

**Comment by lslove10010** [comment]
是新的呢，用passwall，paswall2是这样，openclash也是这样，只要是挂载在cf的网站都无法访问，出国的其他网站访问都正常，我怀疑是不是我部署cf page的域名设置有问题，但是其他的网站访问又正常，目前我在baidu或google都没找到有人提出相似的问题，所以想问问俑哥大佬有没有遇到这种情况

**Comment by yonggekkk** [comment]
我这里都很正常。。更新下你的浏览器版本，或者换个节点配置试试
