### ISSUE TITLE
telegram推送失效

### ISSUE THREAD

**Issue by ntbowen** [yonggekkk/openwrt_win64-ddns-cdnip#2]
最近收不到TG推送了，用ssh执行了一下脚本返回错误信息：TG推送失败，请检查TG机器人token和ID，但实际上token和ID都是正确的，我用其他推送工具能正确推送，请勇哥帮忙看看。

**Comment by yonggekkk** [comment]
> 最近收不到TG推送了，用ssh执行了一下脚本返回错误信息：TG推送失败，请检查TG机器人token和ID，但实际上token和ID都是正确的，我用其他推送工具能正确推送，请勇哥帮忙看看。

一般理解为运行推送时，网络处理非代理状态。。

**Comment by ntbowen** [comment]
> > 最近收不到TG推送了，用ssh执行了一下脚本返回错误信息：TG推送失败，请检查TG机器人token和ID，但实际上token和ID都是正确的，我用其他推送工具能正确推送，请勇哥帮忙看看。
> 
> 一般理解为运行推送时，网络处理非代理状态。。

是不是还没来得及代理就开始推送了，能不能增加推送延迟时间

**Comment by yonggekkk** [comment]
> > > 最近收不到TG推送了，用ssh执行了一下脚本返回错误信息：TG推送失败，请检查TG机器人token和ID，但实际上token和ID都是正确的，我用其他推送工具能正确推送，请勇哥帮忙看看。
> > 
> > 
> > 一般理解为运行推送时，网络处理非代理状态。。
> 
> 是不是还没来得及代理就开始推送了，能不能增加推送延迟时间

目前已经设置30秒以上了，大多数人都能正常推送。。所以我也不确定是是固件？网络？软路由设置？的问题

**Comment by ntbowen** [comment]
> > > > 最近收不到TG推送了，用ssh执行了一下脚本返回错误信息：TG推送失败，请检查TG机器人token和ID，但实际上token和ID都是正确的，我用其他推送工具能正确推送，请勇哥帮忙看看。
> > > 
> > > 
> > > 一般理解为运行推送时，网络处理非代理状态。。
> > 
> > 
> > 是不是还没来得及代理就开始推送了，能不能增加推送延迟时间
> 
> 目前已经设置30秒以上了，大多数人都能正常推送。。所以我也不确定是固件？网络？软路由设置？的问题

好吧，我找找其他原因，如果能自己设置延时就更好了，或者像有些推送工具，在不关代理的情况下，可自行先做个推送测试确保推送功能正常

**Comment by yonggekkk** [comment]
> > > > > 最近收不到TG推送了，用ssh执行了一下脚本返回错误信息：TG推送失败，请检查TG机器人token和ID，但实际上token和ID都是正确的，我用其他推送工具能正确推送，请勇哥帮忙看看。
> > > > 
> > > > 
> > > > 一般理解为运行推送时，网络处理非代理状态。。
> > > 
> > > 
> > > 是不是还没来得及代理就开始推送了，能不能增加推送延迟时间
> > 
> > 
> > 目前已经设置30秒以上了，大多数人都能正常推送。。所以我也不确定是固件？网络？软路由设置？的问题
> 
> 好吧，我找找其他原因，如果能自己设置延时就更好了，或者像有些推送工具，在不关代理的情况下，可自行先做个推送测试确保推送功能正常

已加入自定义，下回更新

**Comment by yonggekkk** [comment]
已更新支持
