### ISSUE TITLE
关于脚本里修改host的问题

### ISSUE THREAD

**Issue by tianhbd** [yonggekkk/openwrt_win64-ddns-cdnip#20]
之前时不时会存在优选的IP无法同步到cf的问题，我反复测试，发现问题出在脚本每次都会把固定的IP绑定到api.cloudflare.com，可能cf的ip变化，导致无法同步结果，所以，把脚本里的相关语句删除就没问题了。前提应该是需要路由器本身能避免dns污染，否则解析不到正确的ip。

**Comment by yonggekkk** [comment]
是的，有影响，最新版应该删除了这部分了
