### ISSUE TITLE
勇哥能否添加一个指定地区功能

### ISSUE THREAD

**Issue by lyp88997** [yonggekkk/openwrt_win64-ddns-cdnip#25]
勇哥，能否添加一个指定地区功能，自动优选后IP地区变动导致Netflix播放异常，固定地区可减少这样的情况，目前是自动测速后又来手动解析固定地区，希望能写在脚本里，谢谢勇哥

**Comment by yonggekkk** [comment]
有可能你指定的国家选择不到。。。

**Comment by lyp88997** [comment]
> 有可能你指定的国家选择不到。。。

可以的，我挂在阿里云服务器上能选到，只是有时候有一两个其他地区的

**Comment by yonggekkk** [comment]
这个以后更新再说
