### ISSUE TITLE
解析到域名个数少了

### ISSUE THREAD

**Issue by ainp** [yonggekkk/openwrt_win64-ddns-cdnip#27]
测速完成5个，但解析到域名才4个(有时候更少，具体请看下图:),昨天重新安装了脚本（以前的没有问题）
![截屏2023-12-07 09 15 53](https://github.com/yonggekkk/openwrt_win64-ddns-cdnip/assets/9693302/52a5e0c3-7830-4170-90e3-3107e47ee2b7)
![截屏2023-12-07 09 23 01](https://github.com/yonggekkk/openwrt_win64-ddns-cdnip/assets/9693302/061ec06d-9506-4c3c-98ec-2fddbb70c409)

**Comment by yonggekkk** [comment]
。。。我看看，脚本，等下更新下。。

**Comment by yonggekkk** [comment]
> 。。。我看看脚本，等下更新下。。

**Comment by yonggekkk** [comment]
可以再重装试试
