### ISSUE TITLE
12.6的脚本安装不了jq，是不是忘记弄了

### ISSUE THREAD

**Issue by zkf0802** [yonggekkk/openwrt_win64-ddns-cdnip#29]
![微信截图_20231209121811](https://github.com/yonggekkk/openwrt_win64-ddns-cdnip/assets/34957036/d2d626af-fdf9-4414-bfbb-112a94b8c1bc)

**Comment by zkf0802** [comment]
![Uploading 微信截图_20231209121811.png…]()

**Comment by yonggekkk** [comment]
已更新，你再试试

**Comment by zkf0802** [comment]
> 已更新，你再试试

我还有个问题  就是最近测速都测不了，是我本地的问题吗

**Comment by yonggekkk** [comment]
> > 已更新，你再试试
> 
> 我还有个问题 就是最近测速都测不了，是我本地的问题吗

测速问题：端口、测速地址、官方IP，反代IP。。这些因素你都可以变，，本地当然也有可能出问题。
