### ISSUE TITLE
域名解析能否把同一地区IP放入一个A记录下

### ISSUE THREAD

**Issue by ntbowen** [yonggekkk/openwrt_win64-ddns-cdnip#3]
现有的脚本如果域名解析的话，优选的IP是一个一个放进设定好的域名里，就是一个域名对应一个IP，能不能把识别成同一地区的IP放进同一个A记录里，比如193.122.114.70、132.145.81.109、193.123.249.216所在地区都是KR，能不能都归在kr.xxx.xxx，（xxx.xxx是cloudflare自选域名）,类似一个优选域名的功能。

**Comment by yonggekkk** [comment]
> 现有的脚本如果域名解析的话，优选的IP是一个一个放进设定好的域名里，就是一个域名对应一个IP，能不能把识别成同一地区的IP放进同一个A记录里，比如193.122.114.70、132.145.81.109、193.123.249.216所在地区都是KR，能不能都归在kr.xxx.xxx，（xxx.xxx是cloudflare自选域名）,类似一个优选域名的功能。

快了，过几天与win平台同步更新。

**Comment by yonggekkk** [comment]
不过目前不分地区，其实地区也没必要。。。

**Comment by ntbowen** [comment]
> > 现有的脚本如果域名解析的话，优选的IP是一个一个放进设定好的域名里，就是一个域名对应一个IP，能不能把识别成同一地区的IP放进同一个A记录里，比如193.122.114.70、132.145.81.109、193.123.249.216所在地区都是KR，能不能都归在kr.xxx.xxx，（xxx.xxx是cloudflare自选域名）,类似一个优选域名的功能。
> 
> 快了，过几天与win平台同步更新。与视频教程一起发布

openwrt的脚本啥时候和win版同步啊，pushplus希望也放到脚本里，或者考虑支持一下其他的微信推送方式，比如serverchan和企业微信

**Comment by yonggekkk** [comment]
已更新支持
