### ISSUE TITLE
Custom script

### ISSUE THREAD

**Issue by tiam400** [yonggekkk/openwrt_win64-ddns-cdnip#30]
Good time dear friend
Is it possible to edit this script and write a special script for me?
What I want you to do is that instead of searching for CloudFur IPs, I will give you a specific number of IPs and change these IPs in my subdomain at specific times.
It means that it does not scan, for example, if I give 10 IPs, it will only change these 10 IPs every 2 hours in the cloud record.
Tell me the cost, I can pay you with digital currency

**Comment by yonggekkk** [comment]
No plans at the moment
