### ISSUE TITLE
windows eddition problem

### ISSUE THREAD

**Issue by omid650** [yonggekkk/openwrt_win64-ddns-cdnip#33]
Dear Yong
first of all, thank you very much for contributing this useful project
I have problem for running windows edition when I execute 一条龙优选IP.exe got : this error message :

Traceback (most recent call last):
  File "110.py", line 211, in <module>
NameError: name 'exit' is not defined
[20844] Failed to execute script '110' due to unhandled exception!
批量删除CF域名解析.exe error : 
没有找到指定的 DNS 记录
恢复hosts文件错误: [Errno 13] Permission denied: 'C:\\Windows\\System32\\drivers\\etc\\hosts'

please advise

**Comment by yonggekkk** [comment]
Right-click the application and run it as administrator

**Comment by omid650** [comment]
I did it but same problem occurs
![image](https://github.com/yonggekkk/openwrt_win64-ddns-cdnip/assets/129746313/fbd9b65c-19df-475e-ad63-fca49d35e80a)

**Comment by yonggekkk** [comment]
use win10
