### ISSUE TITLE
未达到目标数量时一直等待

### ISSUE THREAD

**Issue by HeriseEx** [yonggekkk/openwrt_win64-ddns-cdnip#35]
windows下运行脚本，测速队列跑完但是没有达到目标数量就会一直卡在测速等待。测速队列数量似乎与目标数量相关？目标减少之后队列数量也减少，导致测速任务似乎更难进入下一步？

**Comment by HeriseEx** [comment]
可以发源码的话请发这个邮箱： observer@theroot.today，感谢。

**Comment by yonggekkk** [comment]
测试应用全是引用这个项目的https://github.com/XIU2/CloudflareSpeedTest

**Comment by yonggekkk** [comment]
> 测速应用程序全是引用这个项目的https://github.com/XIU2/CloudflareSpeedTest

**Comment by HeriseEx** [comment]
方便发一下这个项目的源码吗 我想做一点修改

**Comment by yonggekkk** [comment]
cdnip.sh参数执行文件本来就是开源的，你可以随便更改

**Comment by HeriseEx** [comment]
我想改一下windows的

**Comment by yonggekkk** [comment]
> 我想改一下windows的

已发

**Comment by HeriseEx** [comment]
收到 感谢
