### ISSUE TITLE
甬哥 这个项目是否可以放到手机里用TERMUX运行呢

### ISSUE THREAD

**Issue by jwmjazz** [yonggekkk/openwrt_win64-ddns-cdnip#36]
甬哥 这个项目是否可以放到手机里用TERMUX运行呢，没用软路由，电脑不方便开的时候。

**Comment by yonggekkk** [comment]
当然。本身就支持linux，插件选择无代理就行。

**Comment by jwmjazz** [comment]
我成功了   Termux 需要有root权限   虚拟一下debian 就可以优选了 
打开 Termux 应用，输入 pkg update && pkg upgrade 并回车，更新 Termux 的软件源和软件包。
输入 pkg install proot-distro 并回车，安装 proot-distro 软件包。
[输入 proot-distro list 并回车，查看支持的 Linux 发行版及其别名。目前支持的发行版有 Alpine Linux, Arch Linux, Debian, Fedora, Gentoo, OpenSUSE, Ubuntu 和 Void Linux
输入 proot-distro install <alias> 并回车，安装您想要的 Linux 发行版，其中 <alias> 是发行版的别名，例如 proot-distro install debian。
[输入 proot-distro login debian 并回车，启动 Linux 发行版的 shell 会话，您可以在其中执行 Linux 命令和安装软件包

进入debian   就接着勇哥的  软路由步骤了

**Comment by jwmjazz** [comment]
勇哥  这个可以做个视频 手机优选   我现在只能优选你得IP池的， 我现在还没找到 IP4.TXT 文件夹  更换里面的IP . 希望出一期视频

**Comment by yonggekkk** [comment]
> 勇哥 这个可以做个视频 手机优选 我现在只能优选你得IP池的， 我现在还没找到 IP4.TXT 文件夹 更换里面的IP . 希望出一期视频

选择官方IP，可以手动添加自定义IP库

**Comment by jwmjazz** [comment]
我在手机找不到 对应的txt   bash 进去修改 也没有对应的选项

**Comment by yonggekkk** [comment]
> 我在手机找不到 对应的txt bash 进去修改 也没有对应的选项

这个目前只能手动进入路径文件修改

**Comment by jwmjazz** [comment]
我找到了
安装  质感文件app   点击左上角三条杠   点添加存储   点外部储存   在点左上三条杠  选termux   在 cfpopw  文件下下的  IP.TXT 复制IP 进去就行了

**Comment by yonggekkk** [comment]
> 我找到了 安装 质感文件app 点击左上角三条杠 点添加存储 点外部储存 在点左上三条杠 选termux 在 cfpopw 文件下下的 IP.TXT 复制IP 进去就行了

yes

**Comment by jwmjazz** [comment]
失败了  没法修改IP.TXT

**Comment by yonggekkk** [comment]
> 失败了 没法修改IP.TXT

报什么错？用官方IP模式下进行

**Comment by jwmjazz** [comment]
我现在是被termux  root 卡住了，termux装了 debian 后可以运行，但是找不到路径。但是在proot.py 后，又没法执行 @yonggekkk 
![Screenshot_20240103_193130_com termux](https://github.com/yonggekkk/openwrt_win64-ddns-cdnip/assets/140404991/0003821d-694a-4e81-831a-39aedfef1311)

**Comment by yonggekkk** [comment]
网络下载失败吧。。
