### ISSUE TITLE
优选后ip解析域名比直接填写域名要更加不稳定！

### ISSUE THREAD

**Issue by kaige1116** [yonggekkk/openwrt_win64-ddns-cdnip#38]
勇哥你好，按照你的教程成功优选了ip，之后解析到cf绑定域名里，经常性断连，比直接填写ip要不稳定的多。不知道是不是我哪里设置出了问题。(cf绑定的域名解析家里的ipv6，有时候也不能访问，间歇性出现这个情况)

**Comment by yonggekkk** [comment]
当然，单ip与前置大厂域名肯定比自建稳点了！
