### ISSUE TITLE
10个域名，10个更新IP,每次只有不到一半更新成功，不知为何？

### ISSUE THREAD

**Issue by isaac574** [yonggekkk/openwrt_win64-ddns-cdnip#4]
10个域名=CLOUDFLARE二级域名，比如说01.XXX.EU.ORG,.......10.XXX.EU.ORG,
是否要改为JAN.XXX.EU.ORG,FEB.XXX.EU.ORG..........DEC.XXX.EU.ORG？

**Comment by yonggekkk** [comment]
下期修得这个问题。主要是CF网络不稳

**Comment by isaac574** [comment]
谢甬哥，有数了。
