### ISSUE TITLE
pve虚拟机下无法使用

### ISSUE THREAD

**Issue by Jasonpan19930920** [yonggekkk/openwrt_win64-ddns-cdnip#41]
Cloudflare账号登陆成功!
当前工作模式为ipv4
OpenClash Already Stop!
已停止openclash
# XIU2/CloudflareSpeedTest v2.2.4 

2024/01/25 19:14:20 open ip.txt: no such file or directory
优选IP中断，未生成result.csv文件，请尝试更换端口或者重新执行一次
TG_api请求超时,请检查网络是否重启完成并是否能够访问TG
TG推送失败，请检查TG机器人token和ID
未配置PushPlus推送

甬哥有什么办法解决么

**Comment by yonggekkk** [comment]
下载反代IP库，检查下网络。。。。换成官方IP试试
