### ISSUE TITLE
勇哥你好这个脚本的代码可以发我吗，

### ISSUE THREAD

**Issue by liluosheng** [yonggekkk/openwrt_win64-ddns-cdnip#42]
我找这个找了很久了，我有一个是哪个不知道哪个up推荐的可以解析一个ip，一个域名的，但是那样在优选gcore的时候用着很不行，谢谢大佬，麻烦发我一下哈

**Comment by yonggekkk** [comment]
脚本只支持CF，执行文件cdnip.sh本身就是明显文，可以直接修改

**Comment by liluosheng** [comment]
看到了谢谢
