### ISSUE TITLE
优选一条龙WIN版希望能增加限制输出数量功能。

### ISSUE THREAD

**Issue by cheetahchen** [yonggekkk/openwrt_win64-ddns-cdnip#44]
原版[CloudflareSpeedTest]可以通过`-dn 10 -p 5`这样的参数配置剔除掉部分延迟低但速度不佳的IP。希望能重新编译支持`-p`参数

**Comment by yonggekkk** [comment]
cf_dn就是-p参数

**Comment by cheetahchen** [comment]
解决了，实测cf_dn是-dn参数，我增加cf_p，你程序自己翻译成-p了。建议可以修改README ：）
