### ISSUE TITLE
议题已解决

### ISSUE THREAD

**Issue by Kara-ism** [yonggekkk/openwrt_win64-ddns-cdnip#45]
议题已解决，关闭议题

**Comment by yonggekkk** [comment]
那两个文件仅下载与交互功能，主要文件在cdnip.sh明文中可修改

**Comment by Kara-ism** [comment]
> 那两个文件仅下载与交互功能，主要文件在cdnip.sh明文中可修改

好的，谢谢勇哥，我再试看看，谢谢！ :)
