### ISSUE TITLE
一条龙优选IP电脑版 优选环境检查不到ipv6环境，请查证，谢谢

### ISSUE THREAD

**Issue by xinycq** [yonggekkk/openwrt_win64-ddns-cdnip#48]
我的ipv6环境是正常的以前使用一条龙电脑版也能正常优选ipv6,大约1周前出现“经检测，当前网络仅支持IPV4、无IPV6”提示，我的电脑随时都能访问ipv6的梯子和网站。
同一时间使用勇哥的另一个软件  ”CF优选官方IP(电脑版)“ 就正常

拜托甬哥看看是哪里出了问题

**Comment by yonggekkk** [comment]
在哪测的？

**Comment by xinycq** [comment]
电脑 路由 光猫 重启了很多次了，问题依旧   单位电脑  家里的电脑 都是同样的问题

**Comment by xh11123** [comment]
我也发现这个问题了,使用"CF优选官方IP(电脑版)"可以识别到v4+v6双环境,但是用这个一条龙就是提示只有v4没有v6
我的cf-vless一直使用的v6,所以v6是肯定没问题的

**Comment by yonggekkk** [comment]
要改下了，冇空更新下

**Comment by xinycq** [comment]
谢谢甬哥
