### ISSUE TITLE
勇哥你好！更新ddns老是不成功，旧的记录也不会删除

### ISSUE THREAD

**Issue by vbskycn** [yonggekkk/openwrt_win64-ddns-cdnip#49]
勇哥你好！

我用的是多个IP解析到一个域名的方式

![image](https://github.com/yonggekkk/openwrt_win64-ddns-cdnip/assets/34542650/166d5a78-1801-4248-874e-b1e3feecf65f)

5个IP经常性只能成功导入2个，可以更新到CF，但是CF上面老的解析记录没有删除

导致CF上的有好多条记录，如果IP过期，那就会造成这个优选域名有时无效。

请看看

**Comment by yonggekkk** [comment]
这个只能用工具批量删除或者单个删除了，其实还是1对1稳点
