### ISSUE TITLE
openwrt 23.05 版本问题(多个优选IP解析到一个域名)

### ISSUE THREAD

**Issue by ainp** [yonggekkk/openwrt_win64-ddns-cdnip#5]
输入Telegram机器人用户ID: 

是否启用Pushplus微信通知(回车默认不启用，选择1启用): 
cdnip.sh: line 1: syntax error near unexpected token `newline'
cdnip.sh: line 1: `<!DOCTYPE html>'
root@ImmortalWrt:~# cdnip.sh
-ash: cdnip.sh: not found

**Comment by yonggekkk** [comment]
再试下！更新好了
