### ISSUE TITLE
能不能有个opwrt的单独的cf_dns解析工具

### ISSUE THREAD

**Issue by socpio** [yonggekkk/openwrt_win64-ddns-cdnip#50]
甬个大佬，最近用别的方法弄了个IP集，想在opwrt计划任务解析到cd自定义域，有没有类似电脑端的cfup.exe的程序，谢

**Comment by yonggekkk** [comment]
用官方模式！替换ip.txt就行！视频有说

**Comment by socpio** [comment]
> 用官方模式！替换ip.txt就行！视频有说

iStoreOS上，使用最新的脚本，替换了ip.txt，选择了官方，但是result.csv并没有更新，dns解析的还是老IP

**Comment by yonggekkk** [comment]
切换为官方模式，自定义的IP格式要与IP.TXT一样
