### ISSUE TITLE
op的ipv6没法优选

### ISSUE THREAD

**Issue by zkf0802** [yonggekkk/openwrt_win64-ddns-cdnip#52]
op的v6是可以用的，但是脚本识别不到v6
![微信截图_20240715130944](https://github.com/user-attachments/assets/35101962-5877-4ddd-9dce-d9bb5aa7faa8)
![微信截图_20240715131022](https://github.com/user-attachments/assets/fc9204c8-3329-466c-ac5e-dedbcf82042e)

**Comment by yonggekkk** [comment]
输入curl -6 ip.sb 会显示IPV6地址吗

**Comment by zkf0802** [comment]
-6不行，不用参数有ipv6
![微信截图_20240715130944](https://github.com/user-attachments/assets/8291f9ea-bc91-4a66-bb27-b504feb11b0b)

**Comment by yonggekkk** [comment]
能显示为2409开头的不？

**Comment by zkf0802** [comment]
没有

**Comment by yonggekkk** [comment]
不清楚你OP的布局了，检测的确有问题
