### ISSUE TITLE
能否添加解析ip数量

### ISSUE THREAD

**Issue by YingXiaoMo** [yonggekkk/openwrt_win64-ddns-cdnip#54]
result.csv好像只能保存10个ip，配置里设置更多可以测速选出来，但是这里只有10个，剩下的都不会保存
![QQ_1721526018841](https://github.com/user-attachments/assets/cad406c3-9c73-488d-a70a-e79ac2f90377)
![QQ_1721526062164](https://github.com/user-attachments/assets/368c81f0-5044-4634-8baa-26857ab980f6)

**Comment by yonggekkk** [comment]
是的！暂限制10个！一般也够用了

**Comment by YingXiaoMo** [comment]
> 是的！暂时限制10个！一般也够用了

改了好几遍都是10个，还以为是哪设置错了，原来是这样
