### ISSUE TITLE
勇哥 这个脚本如何使用自己的IP库

### ISSUE THREAD

**Issue by billy74** [yonggekkk/openwrt_win64-ddns-cdnip#62]
这个脚本真的十分完善了，唯一的不足就是每次都会去重新下载ip库，是否考虑增加一个使用自定义ip库的参数，方便以后无法下载时还可以自定义ip库

**Comment by billy74** [comment]
我是指反代IP库，目前每次使用这个模式都会重新下载覆盖掉，这让我很头疼

**Comment by yonggekkk** [comment]
可以自定义，选择官方IP模式，改IP.txt里的内容即可
