### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by ainp** [yonggekkk/openwrt_win64-ddns-cdnip#7]
![截屏2023-10-22 下午9 02 07](https://github.com/yonggekkk/openwrt_win64-ddns-cdnip/assets/9693302/df55bc86-6ab3-42e8-accd-6db58790a493)

**Comment by gaodeng520** [comment]
不能创建文件夹，在root目录运行，或者更改cdnip.sh文件

**Comment by gaodeng520** [comment]
你可以关闭提问了
