### ISSUE TITLE
希望支持自定义优选列表

### ISSUE THREAD

**Issue by gaodeng520** [yonggekkk/openwrt_win64-ddns-cdnip#8]
希望支持自定义反代ip优选列表，虽然可以在cdnip.sh中改，但每次测速都要从zip.baipiao.eu.org下载txt文件
所以希望单独新增一个功能，使用户可以从其他渠道获取ip

**Comment by yonggekkk** [comment]
自定义ip列表可在官方ip时的ip.txt中增改，每次测速固定，不会更新

**Comment by tianhbd** [comment]
正向的可以自定义，反代的把ip.txt文件替换了不起作用，还是会从原来的地方下载。

**Comment by yonggekkk** [comment]
> 正向的可以自定义，反代的把ip.txt文件替换了不起作用，还是会从原来的地方下载。

是的，你必要改为官方IP模式进行自定义，反代IP自动更新覆盖，不支持自定义

**Comment by ymyuuu** [comment]
你咋知道是从zip.baipiao.eu.org下载的反代IP的txt文件，你是从甬哥那个脚本文件中哪个文件看到的代码

**Comment by yonggekkk** [comment]
> 你咋知道是从zip.baipiao.eu.org下载的反代IP的txt文件，你是从甬哥那个脚本文件中哪个文件看到的代码

的确是下载反代IP的地址。哈哈
