### ISSUE TITLE
希望勇哥增加软路由一次优选两种IP（IPV4、IPV6）多个端口IP的功能。

### ISSUE THREAD

**Issue by xinycq** [yonggekkk/openwrt_win64-ddns-cdnip#9]
现在软路由上面只能一次优选一种IP的一个端口，能不能麻烦甬哥增加一个功能选项，可以一次优选两种IP的多个端口，分步运行。谢谢！！
不知道我描述清楚没有，举个例子：
我现在软路由上面定时优选IPv4的反代IP，同时我也需要软路由能够优选IPv6的官方IP。
现在的脚本只能完成一种，我想两种IP都交给软路由优选一次完成

**Comment by yonggekkk** [comment]
了解你的意思。目前没排上日程，，再说吧。。哈哈
